language: ruby
rvm:
  - 2.3.1
sudo: false
cache: bundler
bundler_args: --without production
before_install:
  - export TZ=America/Los_Angeles
  - gpg --passphrase $KEY -d -o config/application.yml config/application.yml.asc
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
script:
  - cp config/database.yml.test config/database.yml
  - mkdir -p public/stylesheets/venue && touch public/stylesheets/venue/default.css
  - bundle exec rake db:setup
  - bundle exec rake ci:tests
after_script:
  - rm -f config/application.yml