title: Audience1st
description: Reconnecting community theaters with their communities
google_analytics: 
show_downloads: true
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
  - jekyll-sitemap
